### ISSUE TITLE
New environment configuration is broken on node-webkit

### ISSUE THREAD

**Issue by oteren** [onsip/SIP.js#151]
Hi.

You are using the global. keyword in your environment_browser setup.
Why are you not using window. to get the references to rtc, websocket etc? 
If you run this in node-webkit you will get a conflict, as there you will have a global object that takes care of cross window contexts.

I renamed all global. to window. in environment_browser.js and it seems to work just fine.

**Comment by joseph-onsip** [comment]
Hi @oteren, thanks for the report! For context, here's where some of the relevant changes took place:

* `global` instead of `window`: https://github.com/onsip/SIP.js/commit/fc1999572382b24d62ec91bc64dee3eeeb6abcb4
* environment.js: https://github.com/onsip/SIP.js/commit/9a2b08943414a1ba83745a63035c9cb11b8decfd
* environment_browser.js: https://github.com/onsip/SIP.js/commit/8a538896bf268f8760eb35b628abac0eca62cd3f

As mentioned in the commit messages, these changes were made to help support non-browser environments, such as Node. In the past, I've [suggested](https://github.com/onsip/SIP.js/issues/98#issuecomment-56074034) that NW.js users run the browserified build to avoid problems with `global` references, but it be nice if that wasn't necessary.

Unfortunately, simply replacing `global` with `window` in environment_browser.js causes a ReferenceError when running in Node (something that the automated test suite currently fails to check :disappointed:), so something a little more complex will be needed to ensure full platform compatibility. Pull requests are welcome :)

Alternatively, you could require `sip.js/src/SIP` directly and supply it with an NW.js-compatible environment, similarly to how [index.js](https://github.com/onsip/SIP.js/blob/09a570ccc4467df7bbbb626837fef758fce3e1a0/src/index.js) does it.

**Comment by wakamoleguy** [comment]
> Alternatively, you could require sip.js/src/SIP directly and supply it with an NW.js-compatible environment, similarly to how index.js does it.

This would be the preferred method.  One of the reasons why such a thing exists is precisely because we cannot anticipate all of the different JavaScript environments that users will choose.  Once an environment becomes popular enough, we can take the time to bring the support into the core library.  That said, in this case it does look like Joseph's working on using a third top-level variable that may cover both cases.  If that "just works," we should merge it in.

**Comment by joseph-onsip** [comment]
Yup, I was curious about it and got it "just working" in [`nw`](https://www.npmjs.com/package/nw). @oteren, can you confirm that this works for you?
