### ISSUE TITLE
Hacking protection - How to hide the username, password, url of SIP Server?

### ISSUE THREAD

**Issue by shamun** [onsip/SIP.js#157]
I have SIP server, Username, Password to include in Javascript for call termination. 
How can i hide the credentials to be viewed by anyone from browser?

```
  var config = {
    uri: 'sip:HIDEME@HIDME.com',
    wsServers: 'wss://HIDME',
    authorizationUser: 'HIDME',
    password: 'HIDME',
    register: true
  }
```

**Comment by wpp** [comment]
Don't think thats possible. 

> there is no way to protect javascript intended to run in a browser from a determined viewer.

[see](http://stackoverflow.com/a/6869371/980524)

And also:

https://github.com/onsip/SIP.js/issues/139

**Comment by shamun** [comment]
So anyone opening the software can hack the SIP IP, USERNAME, PASSWORD. And send millions of call for FREE? WOW!!!

**Comment by onsip** [comment]
Certainly not. OnSIP is a prime example of this, where we provide a free
WebRTC endpoint to all of our customers, who can and do use it to make
millions of calls. Are we concerned that all of those SIP credentials are
exposed? No, because we protect them. You must enter in a password to have
the server pass down your credentials. We don't load third party scripts in
the same frame. Generally, we take all of the security precautions a
normal, sensitive website would take.

In other cases, we use an unauthenticated SIP.js endpoint and limit its
capabilities server-side.

That said, there are feasible limitations, though no worse than your
typical desk phone. Anybody walking by your desk could pick up your phone
as easily as your laptop and make "MILLIONS"* of calls.

SIP.js is just a library, not a complete security solution.

Also, I am currently underground. I see you made several other posts and
Issues with further questions. I'll be sure to get to those when I am above
ground again.

Cheers, and thank you for giving SIP.js a try.

-Will

*I do hope your server will detect that as potential fraud long before real
damage is done, right?

**Comment by wakamoleguy** [comment]
I'm going to close out this issue, as the application can take security measures similar to those I mention above, and as wpp mentioned, a SIP.js feature to help is being discussed in #139.
