### ISSUE TITLE
Only accept event is triggered?

### ISSUE THREAD

**Issue by invokercd** [onsip/SIP.js#176]
Hey guys.
I've a little bit confused about **bye** event, it's just don't triggered.
The only event that working is **invite**.
So, what I've tried:
```
ua.on('bye', isbye())
```
For **invite** event:
```
ua.on('invite', handleInvite())
```
In _events property bye method is exist:
![_](http://s24.postimg.org/c3yh0lb11/Selection_2015_05_22_22_10_56.png)
I'm using Chromuim 38 on client and FreeSwitch 1.4.18 as Sip proxy, SIP.js 0.7.0 (with 0.5.0 - same result)
Bye responce is OK:
```
BYE sip:ott9eqb4@a4bpip6hk735.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WS 0.0.0.0:5066;branch=z9hG4bKajDQFm4KryrtS
Max-Forwards: 70
From: "890" <sip:890@0.0.0.0>;tag=t0U93amNmHa6g
To: <sip:ott9eqb4@a4bpip6hk735.invalid;transport=ws>;tag=1c7vs3dj1u
Call-ID: 94daef4f-7b56-1233-f9a1-5254006e5c14
CSeq: 75824321 BYE
User-Agent: FreeSWITCH-mod_sofia/1.4.18+git~20150312T185523Z~4eed221b69~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Reason: Q.850;cause=16;text="NORMAL_CLEARING"
Content-Length: 0

```
Need your help. 
Thanks :)

**Comment by james-onsip** [comment]
Hi invokercd,
  This sounds like an odd problem. Your two code snippets have a small error, which leads me to believe your issue may lie in the code you've written. Those two lines should read:

`ua.on('bye', isbye)`
and
`ua.on('invite', handleInvite)`

Adding the extra set of parentheses calls the function as soon as the line is ran, instead of when the event is emitted. Whatever those functions return when given no arguments is what is currently being called (or attempting to be called, it may not be a function). If that is what you expect, then those lines are ok.

That said, please take issues like this to our [mailling list](https://groups.google.com/forum/#!forum/sip_js). Once we've determined it as an issue with the library, the conversation can move back here. I'm closing this issue, but feel free to open a topic in the mailing list if the above changes did not fix your problem, and we can continue from there.

Thanks,
James
