### ISSUE TITLE
how to create conference call in sip.js???

### ISSUE THREAD

**Issue by meet1** [onsip/SIP.js#201]
i want to create conference call through sip.js

**Comment by wakamoleguy** [comment]
Conference calls are not provided as a basic building block of SIP.js.  To create conference calls, you can either create multiple one-to-one sessions between participants, or use a server-side solution such as an MCU or SFU.  We do not consider the lack of a 'conference' API method to be a bug or Issue, rather than an application-specific implementation choice.

**Comment by meet1** [comment]
thanks...i having create an application

**Comment by belloviniciusf** [comment]
Hi, @meet1 . I think you already solved your problem, but in this week I started to work in same task on my job and searching I found your question. After some searching and testings, I used the code available on https://groups.google.com/forum/#!topic/jssip/iT0qmLfRZhw and it works! 
If this is not appropriate to share, my apologies to the contributors from onsip.

**Comment by md-riaz** [comment]
> Hi, @meet1 . I think you already solved your problem, but in this week I started to work in same task on my job and searching I found your question. After some searching and testings, I used the code available on https://groups.google.com/forum/#!topic/jssip/iT0qmLfRZhw and it works! If this is not appropriate to share, my apologies to the contributors from onsip.

@belloviniciusf can you please share the code? The google group is not accessable

**Comment by ChristianDude** [comment]
As md-riaz stated, the group is dead. Please post the workable solution on this thread :).
