### ISSUE TITLE
conference call

### ISSUE THREAD

**Issue by meet1** [onsip/SIP.js#206]
i am unable to create conference call in sip.js ..plz can someone help me in creating conference call as  my web appplication is using sip.js and i have already create call ,hold ,unhold and transfer in sip.js .it's similar to this(  http://code.google.com/p/sip-js/  )...

**Comment by wakamoleguy** [comment]
Hi,

For support questions like these, please open a thread [on our Mailing List](https://groups.google.com/forum/#!forum/sip_js).  We would like to reserve GitHub for feature requests, coding issues and bugs in the library.  Additionally, posting on the mailing list will reach a larger audience of people *using* SIP.js, rather than just the authors.  You may receive more advice there.

Also, this is the third issue you've created for this so far.  Like in [my previous response](https://github.com/onsip/SIP.js/issues/201), SIP.js does not support conference calls explicitly.  You must create them by creating multiple one-to-one sessions, or by using server-side conference software.

Please do not create any more GitHub Issues with this question.  We have answered it to the best of our ability, and it is not the place for it in any case.  Thank you.

-Will
