### ISSUE TITLE
Microsoft Edge support for the WebRTC 

### ISSUE THREAD

**Issue by asiminiceanu** [onsip/SIP.js#223]
Microsoft just released this:
https://blogs.windows.com/msedgedev/2015/05/13/announcing-media-capture-functionality-in-microsoft-edge/

I see that some basic things work on http://webrtc.github.io/samples/
Can you please add support for the latest Edge (what is supported of course)?

**Comment by asiminiceanu** [comment]
Some extra details how was it was done on WebRTC samples page:
https://blog.andyet.com/2015/06/25/webrtc-on-the-edge
https://github.com/webrtc/samples/pull/517

**Comment by james-onsip** [comment]
Hi asiminiceanu,
  Unless a version of Edge released since the launch of Windows 10 has added PeerConnection support, Edge will not work with SIP.js. The articles you linked (dated May 13 and June 25) only mention support for getUserMedia. This means you will be able to do things like picture booths with Microsoft Edge for the time being, but the placing of calls and other SIP.js functionality is still not supported.

This said, we are closely following news and releases from Microsoft, and plan to be Edge-compatible once the necessary APIs are supported.

Thanks,
James

**Comment by asiminiceanu** [comment]
Thanks for the clarification James!

**Comment by urbaniak** [comment]
How about that post on edge dev blog - http://blogs.windows.com/msedgedev/2015/09/18/ortc-api-is-now-available-in-microsoft-edge/?

It looks like there's a similar api to rtcpeerconnection - RTCIceGatherer /RTCIceTransport/RTCDtlsTransport - is it enough to implement sip.js support for edge?

**Comment by Tinet-AaronAn** [comment]
Thanks for the clarification James, but does Microsoft support silimar API like PeerConnection on they ORTC implementation?

**Comment by james-criscuolo** [comment]
Microsoft is working on getting the PeerConnection up to where the rest of the browsers are. I hadn't used http://iswebrtcreadyyet.com/ in a while, but it seems to be up to date on Edge support. Notably, the PeerConnection API box is still yellow, which means partial support.

**Comment by soulofmischief87** [comment]
Has anyone tested  sip.js with edge of lately? I'd like to know the outcome since other items are green now.

**Comment by shiroyuki** [comment]
I tried it today and it still does not work.

**Comment by chornyitaras** [comment]
Just tested Janus webrtc gateway (https://janus.conf.meetecho.com/echotest.html) in latest Microsoft Edge 40.15063.0.0 and it works perfectly. As I can see janus is using PeerConnection. Also I've checked availability of it  in dev console. 
![image](https://user-images.githubusercontent.com/17271728/27971489-8e46c1d0-635b-11e7-8e54-6e4e2cef4942.png)

**Comment by snuggs** [comment]
Oh this is BEAUTIFUL!!!!!
