### ISSUE TITLE
Set TURN server on ACCEPT

### ISSUE THREAD

**Issue by wackazong** [onsip/SIP.js#260]
We thought we could set the TURN servers and credentials also on accept using the same approach as in #250. But this does not seem to work. Is there any way we can set TURN Servers and credentials when a call is incoming?

**Comment by james-onsip** [comment]
Hi wackazong,
I've been looking into this issue this morning, and it looks like we could fix it with little hassle if RTCPeerConnection's 'updateIce' function was implemented correctly. Unfortunately, it looks like they are [still working out some kinks](https://groups.google.com/forum/?fromgroups#!topic/discuss-webrtc/EQ9psfYjCKc).

I hesitate to make the larger change of not creating the MediaHandler until we call accept, so instead, I just completely replace the peerConnection if you pass turnServers or stunServers into the accept function. This also works with the progress function (for early media), but checks are done to ensure that early media calls can not get their peerConnection changed on accept (since media is already set up at that point, so you'd blow it out unknowingly).

Please let me know if this works for you.

Thanks,
James

**Comment by james-onsip** [comment]
I'm going to close this, but feel free to re-open if you are still experiencing issues. The changes can be found in version 0.7.3.

Thanks,
James
