### ISSUE TITLE
Without UDP/TURN connectivity, there's no error notification

### ISSUE THREAD

**Issue by joshuawarner32** [onsip/SIP.js#271]
I have a situation where there's no UDP or TURN connectivity (but there is websocket connectivity) - which of course means SIP.js can't communicate out.  That's fine, but SIP.js doesn't give any sort of error notification, as far as I can tell.  My app just gets 'progress' and 'accepted' events on the Session, and then... nothing.

As for root cause, it looks like the `oniceconnectionstatechange('failed')` never gets handled.  It looks suspiciously like that's what this commented-out code should be doing: https://github.com/onsip/SIP.js/blob/master/src/WebRTC/MediaHandler.js#L157.

However, that code doesn't provide consistent argument values for that event, so I switched to this code instead: https://github.com/joshuawarner32/SIP.js/blob/master/src/WebRTC/MediaHandler.js#L156.

My question is this:
* Is this the right way to fix this problem, or is there a better way?
* Might this change be accepted as a PR?

**Comment by james-onsip** [comment]
Hi Joshua,
  This is a tough one, as ice states are very finicky and tend to change with browser versions. Rather than corner SIP.js into one solution that could people may not be expecting, we emit the event, and leave it to the user to decide what to do.

It looks like the mediaHandler will emit 'iceConnectionFailed' in your situation, so you could set up a listener for that event and that should be enough to catch the situation within your application.

It would definitely be better if SIP.js could handle this internally and you could expect one event to cover all failure cases, but until browsers stabilize a bit more, I think it's safer to stick with the current approach.

Good luck,
James

**Comment by joshuawarner32** [comment]
Ok, seems to be working.  Thanks, James!
