### ISSUE TITLE
Calls autostart after 5 minutes: Invalid Status: 12 

### ISSUE THREAD

**Issue by SirLouen** [onsip/SIP.js#285]
We are having an issue after we switched to TLS: For some reason, call autostart after 5-10 minutes aproximately without "permission" dialing exactly the same sip address that was dialer in the first instance

After the first call finishes it returns an *\* Invalid Status: 12 **
We are not sure if this is an issue or is something that might be misconfigured but we did not experience this before.

Any ideas?

**Comment by james-criscuolo** [comment]
Hi @SirLouen,
  That sounds odd, but i could signify an issue with the signaling, which would either pinpoint a problem on the SIP.js end or otherwise. If you could enable traceSip in your UA configuration and put your logs in a gist, we could look through and help label the issue more accurately.

Thanks,
James

**Comment by SirLouen** [comment]
Hello @james-criscuolo 
Here it is
https://gist.github.com/anonymous/bbd61d6277dae91a9bae

**Comment by james-criscuolo** [comment]
It looks like the 'automatic' call occurs once you re-register. Does your app's code listen for the `register` event before doing certain actions? Maybe using the `once` function instead of the `on` function could fix it wherever you listen for `register`.

As for the invalid state error, I'm not sure about that, but that is not an internal log that is printing that, so maybe something in your code is causing it?

**Comment by egreenmachine** [comment]
Any updates on this? I am going to close it in the next few days as an issue with the end user application if there is no update.
