### ISSUE TITLE
Offerer must use actpass value for setup attribute

### ISSUE THREAD

**Issue by shadmehr** [onsip/SIP.js#287]
When the call is coming into asterisk ,after accepting call by sipjs client (v0.7.2) on chrome (v47.0.2 and v48.0.2) , I ask asterisk to execute REFER between the end points , I got below exception. (It's working well on FireFox 44.0.2) 

Tue Feb 16 2016 17:49:22 GMT-0500 (EST) | sip.invitecontext.mediahandler | Failed to set local answer sdp: Failed to push down transport description: Offerer must use actpass value for setup attribute.
sip.js (2957,28)

**Comment by james-criscuolo** [comment]
Hi @shadmehr,
  This most likely identifies that sdp on another endpoint is being generated in such a way that Chrome can not interpret it properly. If you were able to determine where the sdp is being generated 'improperly,' a hack could be added to our hacks file if it was proven to fix your issue.

Otherwise, this is either a problem with Chrome directly, or with your Asterisk config, so I'm going to close the issue. If you can properly identify the necessary hack, we would certainly accept a PR.

Thanks,
James

**Comment by GMLudo** [comment]
Hi,

I think that these issues should help you to understand the situation:

1. https://github.com/versatica/JsSIP/issues/311
2. https://issues.asterisk.org/jira/browse/ASTERISK-25864
