### ISSUE TITLE
TIMER L expiring

### ISSUE THREAD

**Issue by jmcoimbra** [onsip/SIP.js#292]
Hello,

This is more like a question...

According to [RFC 6026 7.1](https://tools.ietf.org/html/rfc6026#section-7.1), if TIMER L expires in the "Accepted" state, should the code stop signaling and trigger SIP.Session "terminated" event?
Also I've noticed that after a TIMER L is fired there is a scenario that all next INVITEs is going to have TIMER L expired.

Thanks

**Comment by james-criscuolo** [comment]
Hi @jmcoimbra,
  You can see [in Transactions.js](https://github.com/onsip/SIP.js/blob/master/src/Transactions.js#L499) that what you describe is what we expect to happen. This seems like code that doesn't get hit in too many cases, so if there is a bug it's possible it hasn't caused problems for many people and has been dormant for some time.

All of the code for manipulating Timer L is within that file, so that may make it easy for you to debug and determine if what you are seeing is clearly a bug. If it is a bug, and can be clearly reproduced, we'll do what we can to fix it, but a pull request would also be welcome here.

Thanks,
James

**Comment by james-criscuolo** [comment]
I'm going to close this issue, but if you end up discovering anything new please feel free to reopen.
