### ISSUE TITLE
question: how to change mediaOptions during Call?

### ISSUE THREAD

**Issue by fredguth** [onsip/SIP.js#301]
Sorry in advance if this is not the correct channel to ask this kind of question.

I would like to turn on/off the video functionality during a call.  Is it possible?

**Comment by james-criscuolo** [comment]
Hi @fredguth,
  Currently, there are two not-great-but-sure-fire ways to do this (maybe there's more, I just thought of these quick):
- starting a new session then just swapping the sessions, and potentially ending the old one. This would be ok in chrome assuming permissions were already granted, but you'll still get a popup in firefox.
- start the initial session with audio and video, then immediately mute video. Also not great, because both users will see immediately that their camera access has been granted.

Eventually (and it may even be right now, we just haven't had the opportunity to dig into it too deeply) you'll be able to renegotiate your session and add/remove from it as you please. Even at that point, you'll still probably need to deal with a second permissions prompt, so in the end I'm not sure when this will be a seamless transition.

As for correct channels, questions like this usually appear [on our Google group](https://groups.google.com/forum/#!forum/sip_js). I'm going to close this issue, but please feel free to continue this discussion there, in either a new or existing topic.

Thanks,
James

**Comment by fredguth** [comment]
Thanks!
