### ISSUE TITLE
Surviving IP address changes during call sessions

### ISSUE THREAD

**Issue by apparition47** [onsip/SIP.js#311]
I'm using SIP.js on mobile devices and it's been working great. However, when I change networks (i.e. toggle WiFi, which changes the device's IP address), I lose audio. Assuming that I'm able to hook into the network IP change event, how would I reconnect the media streams without ending the call?

Any guidance on where to start would be helpful--Thanks!

**Comment by james-criscuolo** [comment]
Hi @apparition47,
  This is definitely an interesting question, and one I'm not sure there is currently an answer to. There are problems just at the websocket level, which we are yet to solve, which can be seen by toggling your internet connect. If you are quick enough, the call will stay up, but then the UA begins to re-register, and this process breaks the rest of SIP signaling for the call, mainly because reconnecting to the websocket changes the "path" to your user agent. The audio still works in this case, though.

  On top of this, there are also questions at the browser level. I don't know how peerConnections behave under these circumstances, and by your loss of audio I am assuming not well. Any issues at this level would really be out of our hands. I haven't done any research at either level of this problem, but it's possible there may be answers out there for either case. In either instance, slight modifications would probably be necessary for SIP.js, but I can't say for sure.

-James

**Comment by etamme** [comment]
This is an interesting question / problem. As @james-criscuolo said, this is not really something that would be handled within SIP.js, but through a combination of client and server implementation.  

Theoretically you could detect a network change and immediately send a re-INVITE to renegotiate the session, but there are potential complications depending on how your media is being relayed or not - specifically if the media is routing directly to the far end which is a WebRTC endpoint, it would have to be able to deal with the renegotation via a new get user media request, or some how reusing the existing stream.  If you have a DTLS-SRTP capable proxy in the middle such as RTPEngine it may be possible for the proxy to "absorb" that DTLS/ICE renegotiation by acting as an DTLS/ICE-lite client.  

I am curious what you end up trying and what the results of your outcome are.

**Comment by apparition47** [comment]
Interestingly enough, we were thinking the process would be something like what @etamme has suggested. All our calls are already relayed with RTPEngine but we'll have to experiment with an in-call re-INVITE implementation with our client-server setup to see what works.

Thanks for the detailed responses. I know there's nothing actionable here so I'll go close the ticket until we have a chance to test this.

**Comment by ShakeelMirza** [comment]
Hello @apparition47 I implement this schemes for Android Application of VoIP call and I use WebRTC and it enables us to change the IP addresses during live VoIP calls. Means I change my network from Wifi to 4G during live call and my call will not drop.

**Comment by ManikantaJNSVV** [comment]
network change while call going ?
