### ISSUE TITLE
Not parsed failed event in session

### ISSUE THREAD

**Issue by grencik** [onsip/SIP.js#318]
When failed event in session occures in some cases is first argument not parsed into object and just clean string is given.

Code:
```javascript
session.on('failed', function (request) { 
	console.log(request); 
}.bind(this)); 
```

And request variable contains this:

> SIP/2.0 480 Temporarily Unavailable
> Via: SIP/2.0/WSS xxxxxx.com;branch=z9hG4bK5593.1b330d16f44c7e3cf1fd0cc7680b3bfb.0;i=032
> Via: SIP/2.0/TCP 192.168.7.3:5060;received=192.168.7.3;branch=z9hG4bK3ff1a729;rport=5060
> To: <sip:me4gcsln@oil9i2t3hlff.invalid;alias=202.189.129.114~41173~6;transport=ws>;tag=mou9u4n227
> From: "Name Surname" <sip:103@xxxxxxxxx.com>;tag=as2cd6c6ec
> Call-ID: 208fc1f1519d703e6bc5b812637d754e@192.168.7.3:5060
> CSeq: 102 INVITE
> Supported: outbound
> User-Agent: SIP.js/0.7.4
> Content-Length: 0

Instead of
> f {logger: b, headers: Object, status_code: 487, reason_phrase: "Request Terminated", data: "....." ....

This happened to me after rejecting incoming call with `session.terminate()`

**Comment by james-criscuolo** [comment]
Hi @grencik,
This is due to [this line in ServerContext.js](https://github.com/onsip/SIP.js/blob/master/src/ServerContext.js#L73). The return value is just a string, and this is what we place in the emission. Responses are never wrapped similarly to a request, so its not a straightforward answer of what to do here. We could just throw the request in, but then you aren't entirely sure what it was reject with.

I would recommend checking the next argument, status code, as it will hopefully have some more easily parseable information. Alternatively, you are setting the listener on the session object, which has the request within it, so you should be able to access the request from there. I am not sure if that response string would ever be of use, so it's probably worth changing, but I'm not entirely sure what we should change it to at this point. Please let me know if any of these workarounds work for you.

Thanks,
James

**Comment by grencik** [comment]
Hi @james-criscuolo and thank you, for your response.

I can use next argument, but status code is not integer just text representation of it, which is not so "cool". And, I can also parse string message, but obviously there is some function for parsing it. And it is more useble parsed in object than in text.

So, I have to do it otherwise...

**Comment by grencik** [comment]
I used second argument for now....
