### ISSUE TITLE
Only "disconnected" triggered, if server returns 404 

### ISSUE THREAD

**Issue by dennisguse** [onsip/SIP.js#322]
If the Server-URL is wrong (e.g. typo) and the server returns a 404 and closes the connection only a "disconnect"-event is triggered and a reconnect scheduled.
However, this is likely a permanent failure that is not going to resolve itself.

Also, no "connected"-event is emitted.

Option a)
Emit a registrationFailed and stop reconnecting, i.e. let the program interact with the user to resolve the issue.

Option b)
Add another event.

Tested versions 0.7.2 and 0.7.5

**Comment by james-criscuolo** [comment]
Hi @dennisguse,
  The problem here is that connecting and registering are two different operations, so I don't believe we even begin registering during this initial connection (although I could be wrong, I didn't go through the code myself). Our connection logic has always been a little lacking, so it would certainly be a welcome improvement.

In the meantime, does the errorCode on the disconnect event not provide enough information? Our logic could certainly be more informative, but it's possible your use-case can be solved with the code as-is.

Thanks,
James

**Comment by dennisguse** [comment]
Hey,

sadly "disconnected" does not provide a reason (no arguments are passed to callback)...
http://sipjs.com/api/0.7.0/ua/#disconnected

Any other way to access the HTTP status code?

**Comment by james-criscuolo** [comment]
This is the only emission I see: https://github.com/onsip/SIP.js/blob/db37dbcc049aecee352eb2ecdba671ca37e8c03f/src/Transport.js#L132

There is an object with it. We should probably update the documentation...
