### ISSUE TITLE
Much Slower DTLS Handshakes with Chrome 52?

### ISSUE THREAD

**Issue by lylepratt** [onsip/SIP.js#346]
Has anyone else experienced much slower DTLS connection times with Chrome 52 connecting to Freeswitch? This is probably not a SIP.js issue, however, it may be a case for allowing the manual override of using a different (older) algorithm for the handshake security.

If now one else has experienced this, maybe its some other issue we're dealing with.

**Comment by egreenmachine** [comment]
Hi @lylepratt, this is really a discussion for our [mailing list](https://groups.google.com/forum/#!forum/sip_js) so I am going to close the issue here, feel free to continue the discussion there.

We have not seen any slowness in Chrome 52. We did update our openssl version on our servers to support the new dtls algorithm that Chrome was using. I believe we are using the old algorithm on calls that we originate from our freeswitch instances, but there has been no slowness there either.

**Comment by onsip** [comment]
Is this guy an OnSIP user?
