### ISSUE TITLE
not working connecting event

### ISSUE THREAD

**Issue by Dewilas** [onsip/SIP.js#356]
Hello,

I have issue with connecting event. I cant get any log of this event. Here is my code and freeswitch logs:
```
        sipClient.phone = new SIP.UA(sipClient.config);

        sipClient.phone.on('connecting', function(arg) {
            alert('connecting'); // not working
            sipClient.setStatus("Connecting");
        });

        // this event working perfect!
        sipClient.phone.on('connected', function(e) {
            sipClient.setStatus("Connected");
        });
```

Here is log:

Wed Sep 28 2016 14:23:27 GMT+0300 (EEST) | sip.transport | connecting to WebSocket wss://CP1.sip.domain.com:5067

Wed Sep 28 2016 14:23:27 GMT+0300 (EEST) | sip.transport | WebSocket wss://CP1.sip.domain.com:5067 connected
Wed Sep 28 2016 14:23:27 GMT+0300 (EEST) | sip.ua | connection state set to 0

Connection status: Connected

Wed Sep 28 2016 14:23:27 GMT+0300 (EEST) | sip.transport | sending WebSocket message:

Why this connecting event don't work?

**Comment by james-criscuolo** [comment]
Hi @Dewilas,
  I believe the issue is that you have `autostart` enabled (just a guess, as I can't see your config). The code that emits `connecting` is not asynchronous in anyway, so it's likely that the log message occurs before your listener is set up. Disabling `autostart`, then manually calling `connect` once you set up the UA should fix your issue.

James

**Comment by Dewilas** [comment]
@james-criscuolo thank you, it works!
