### ISSUE TITLE
Is it possible to play a MP3 or other audio stream over SIP.js?

### ISSUE THREAD

**Issue by grokify** [onsip/SIP.js#363]
I would like to play a pre-recorded message over an audio connection and was wondering if SIP.js can do this.

I found the following parameters in the docs: `options.media.stream` and `options.media.render`

I also found the following on Stack Overflow and was wondering what is the best way to do this.

* link: http://stackoverflow.com/questions/25104179/asterisk-sip-js-remote-call

Code excerpt:

```js
var audio = new Audio('ring.mp3');
var ua = new SIP.UA(config);

ua.on('invite', function(incomingSession) {
    session = incomingSession;
    audio.play();
    prepareToanswer();
});
```

**Comment by james-criscuolo** [comment]
Hi @grokify,
  Using WebAudio instead of getUserMedia to get your MediaStream, then passing this when accepting your session, should allow you to play audio. If you are looking to play audio before answering, you need to use early media to accomplish this.

  In general, please ask questions like this in our [google group](https://groups.google.com/forum/#!forum/sip_js). We try to keep this space for bugs or confirmed feature requests.

Thanks,
James

**Comment by AntonioMendez** [comment]
> Hi @grokify,
> Using WebAudio instead of getUserMedia to get your MediaStream, then passing this when accepting your session, should allow you to play audio. If you are looking to play audio before answering, you need to use early media to accomplish this.
> 
> In general, please ask questions like this in our [google group](https://groups.google.com/forum/#!forum/sip_js). We try to keep this space for bugs or confirmed feature requests.
> 
> Thanks,
> James

Hi! any example of how to achieve this?

I have the same need of playing an audio file in an active session and every [example](https://www.wakamoleguy.com/2014/flac-over-webrtc-with-sipjs/) I find is outdated or extremely confusing.

Thanks in advance.
