### ISSUE TITLE
Unable to subscribe for multiple users URI's

### ISSUE THREAD

**Issue by umasgn** [onsip/SIP.js#364]
Unable to subscribe for multiple user URI's, It i
![code](https://cloud.githubusercontent.com/assets/12139440/21021001/c25a9010-bd9c-11e6-82de-3a707338f04a.png)
![err](https://cloud.githubusercontent.com/assets/12139440/21021007/c61a5276-bd9c-11e6-9999-3745b594015e.png)

s throwing

**Comment by james-criscuolo** [comment]
Hi @umasgn,
  This error being thrown is harmless. We have an app in production which opens dozens of subscriptions at once (if not more), so I am confident that this works. Although I'm unfamiliar with the syntax, I believe the problem is that you are setting the subscription to a constant, so it will continually overwrite, instead of making a new one everytime.

  If you enable traceSip, you should see multiple SUBSCRIBEs being sent and responded to.

James

**Comment by umasgn** [comment]
Thank you very much for your quick reply. @james-criscuolo. Is there any function to subscribe for multiple uri's ? not single uri each time ?

**Comment by james-criscuolo** [comment]
There is currently no such function, and a function like that would just be a wrapper similar to what you have written, meaning there would be no advantages in terms of SIP.

**Comment by umasgn** [comment]
Thank you very much @james-criscuolo
