### ISSUE TITLE
481 Response Sent on receiving NOTIFY before 200 OK for Subscribe.

### ISSUE THREAD

**Issue by Anshumakkar** [onsip/SIP.js#366]
on Receiving NOTIFY before SUBSCRIBE Response, 481 is sent, as Session is not found in UA sessions.

'''
UA.prototype.findSession = function(request) {
  return this.sessions[request.call_id + request.from_tag] ||
          this.sessions[request.call_id + request.to_tag] ||
          null;
};
'''
Kindly Check

**Comment by egreenmachine** [comment]
Can you be a bit more detailed about what the issue is and what you are looking for?

**Comment by Anshumakkar** [comment]
This is the order in which Issue happens.
a)UE sends SUBSCRIBE to Network.
b) Network sends NOTIFY to UE.[ before 200 OK of SUBSCRIBE]
c) UE sends 481 Response for NOTIFY Request
d) UE receives 200 OK for SUBSCRIBE

as per RFC 6665

 Due to the potential for out-of-order messages, packet loss, and
   forking, the subscriber MUST be prepared to receive NOTIFY requests
   before the SUBSCRIBE transaction has completed.

Kindly check as currently as per Code, UA Session will be filled only after 200 OK for SUBSCRIBE Request has been recieved i.e. after Confirmed Dialog Creation.

**Comment by james-criscuolo** [comment]
This seems to be a bug, as the dialog is only created after receiving a 2xx. The RFC is clear:

> Due to the potential for out-of-order messages, packet loss, and
   forking, the subscriber MUST be prepared to receive NOTIFY requests
   before the SUBSCRIBE transaction has completed.

I can try to put a branch together for this today, and if you can test after that and it checks out, we'll merge.

**Comment by Anshumakkar** [comment]
As this is not an always Issue, I will take the fix and verify the fix as it happens again.

**Comment by james-criscuolo** [comment]
I've committed on my own fork: https://github.com/james-criscuolo/SIP.js/commit/0c257b17ef0e9800096dd87ad72525434efd6261

Please test and let me know if you run into anything. This required a considerable rework of early subscription code, but I was able to test with our application and our use case still works.

**Comment by Anshumakkar** [comment]
Hi James, Thanks for the quick resolution. I will run my test using this commit. Meanwhile I also did the same as you did. Your approach seems better.

**Comment by james-criscuolo** [comment]
Hi @Anshumakkar,
  I saw you left a note regarding why the dialog was 'UAS' instead of 'UAC'. I can no longer find that note, but I did do some digging here and wanted to update you.

  I believe that `type` variable is just for internal use, to allow the Dialog constructor to know whether it's dealing with a response or request for the creation of this dialog. I could understand why creating it 'UAC' would make more sense, but now that we are creating based on the NOTIFY (request) instead of the OK (response), the switch was necessary. You'll see I already have some hacks to make sure the cseq is correctly set. I did attempt to switch this back to 'UAC' this morning, and the hacks are much more significant, to the point where it didn't even make sense to use the constructor.

  On top of this, I do not see anything in the RFC regarding the creation of the dialog. I'm not sure if dialogs are even tracked in this regard, outside of needing to know how they should be created. For now, I'm going to leave the code as is, but please let me know if you find some contradiction in the RFC or this has caused some other problem.

**Comment by Anshumakkar** [comment]
Hi James, Actually I removed my comment as I understood why UAS dialogue is required instead of UAC, as if UAC dialog ia created then the next in dialog request will have wrong To and From Headers filled that will cause in-dialog request to fail.

**Comment by Anshumakkar** [comment]
Issue is fixed .
Thanks @james-criscuolo
