### ISSUE TITLE
Memory waste `pkg`

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#383]
In `SIP.js`, keeping a reference to pkg is a waste of memory since we only use it for static values. The following would be equivalent but would allow the Garbage collector to free `pkg`:

```js
var SIP = Object.defineProperties({}, {
  version: {
    value: pkg.version
  },
  name: {
    value: pkg.title
  }
});
```

**Comment by matthieusieben** [comment]
Note that doing this *may* break compatibility in case some code uses `Object.getPropertyDescriptor()` on `SIP`. The following may be safer:
```js
var pkg = require('../package.json');
var version = pkg.version;
var name = pkg.title;

var SIP = Object.defineProperties({}, {
  version: {
    get: function(){ return version; }
  },
  name: {
    get: function(){ return title; }
  }
});
```

**Comment by matthieusieben** [comment]
The latter solution may still cause a problem if someone would use the following hack:
```js
var sipPkg = require('sip.js/package.json')
sipPkg.title = 'MySIP.js'
```
But do you want to support that case ?

**Comment by james-criscuolo** [comment]
Just pushed the fix for this, thanks again! Upon inspecting, we definitely weren't attempting to support that case, and I think it'd still work if they did that before including SIP.js.

Are you finding these memory issues using another application, or just manually? If you are using something, we'd be interested in incorporating it into our workflow so we can clean these up before committing, or potentially be able to clean up stuff like this on our own. Please let me know.

Thanks,
James

**Comment by matthieusieben** [comment]
This particular one I detected while reading the code of `sip.js`. The others were detected using the Chrome debugger (because we realized that our web app was using more and more memory over time).

I don't know about any tool to automate this. I should investigate the subject though. I'll let you know if I ever do.

Thanks for the quick response & support.

Cheers,
Matth
