### ISSUE TITLE
Write tests for WebRTC.MediaHandler.defaultFactory.isSupported

### ISSUE THREAD

**Issue by joseph-onsip** [onsip/SIP.js#39]
#38 was merged in without tests because I was having trouble getting the testing setup to cooperate. I was going to re-open the pull request, but there doesn't seem to be a way to do that, so here's a ticket instead.

We should test that creating an InviteClientContext/InviteServerContext with `{mediaHanderFactory: SIP.WebRTC.MediaHandler.defaultFactory}` actually ensures that the SIP.WebRTC.* methods are defined.

**Comment by wakamoleguy** [comment]
As it turns out, our tests aren't set up to test this properly.  All of the specs share a single `SIP` object, and several of them use the defaultFactory.  That means that once any one spec calls `isSupported`, the methods will be defined forever.  That is, we don't have a good way to make sure one spec's actions are what caused them to be defined.

On the other hand, if this weren't working, all hell would break loose and nothing would work at all.  This would certainly break lots of tests.

I'm going to close this as a wont-fix for now, but we could possibly revisit it after we stop using real WebRTC functions for other specs.  I've started down this path already with a Rock-Paper-Scissors media handler.
