### ISSUE TITLE
SIP.js Do Not Disturb (DND)

### ISSUE THREAD

**Issue by adekock11** [onsip/SIP.js#394]
Hi guys,

I'm not sure whether this is the correct place to ask. If not, I'm sure you will redirect me.

I use SIP.js together with Asterisk. I know you aren't "Asterisk people" per se, but could you tell me whether it is possible to set an extension to "Do Not Disturb" mode?

From what I understand, DND mode will cause an extension to be able to dial outbound, but the extension will not receive any inbound calls.

I realise that one can manage this on Asterisk side, but I would really like to find a solution where it is managed by SIP.js.

If DND is not possible, do you foresee any problems with the following proposed solution:
- Build a small wrapper around SIP.js
- Add a `this.dnd` variable
- On SIP invite, check `if (this.dnd)`, if `true` reject the session automatically

It is important that the solution works with an Asterisk queue. If a person phones in, joins a queue, queue redirects to an extension and the extension rejects the call, will Asterisk drop the call, or will Asterisk move the call to a next agent?

PS: I've already posted this in Asterisk forums too, but would appreciate *your* input as well

**Comment by james-criscuolo** [comment]
As I understand it, DND is just an autoreject. So invite comes in, and instead of the normal flow, we immediately and automatically reject with a certain code (603 maybe?).

This is something we can add to SIP.js fairly simply, but altering your invite listener to conditionally reject based on your own (`this.dnd`) variable should solve this.

If there is something more to DND, let me know, otherwise this is fairly solvable inside of the library or out. I guess the argument for not including it in the library would be that it may be something people want to customize further.

**Comment by adekock11** [comment]
Hi @james-criscuolo,

Thank you very much for your response. Your suggestion on rejecting the call with a certain code is very good. I'll go read up on which code I should use to ensure Asterisk handles it correctly, and which codes normal SIP hard phones use when you put them into DND mode.

I think it would be a good value add to the library. One can call `busy()` and `unbusy()` methods exactly the same as `register()` and `unregister()`.

From my side I'll be implementing a wrapper class then, just to manage when invite sessions get rejected.

**Comment by adekock11** [comment]
Hi @james-criscuolo,

Just wanted to let you know that I ended up implementing two types of DND. One way is to automatically reject any inbound calls like we discussed.

The other way was to dial a feature code. Since it's an Asterisk server I was able to dial `*78` to go into DND and `*79` to go back to available.
