### ISSUE TITLE
caller id

### ISSUE THREAD

**Issue by salkat** [onsip/SIP.js#40]
How can I get caller id before accepting the call?

Sorry, I didn't find solution in docs, guides and during quick overview the source

**Comment by LTroya** [comment]
I'm trying to get the displayName that I passed throught config object, like this:
    `var config = {
            displayName: 'myDisplayName',
    }`

Then, try to get it with:
    `session.remoteIdentity.displayName`
but it show me the extension, not config's displayName property. 

What I am  doing wrong?

**Comment by wakamoleguy** [comment]
Hi Luis,

`session.remoteIdentity.displayName` should match exactly the display portion of From address in the received INVITE request, or for outbound calls, the To address of the sent INVITE.  If there is no display portion, I believe it will be set to the the user portion of those addresses.

You haven't provided a lot of details about your scenario, but please use the `traceSip` option to verify that the above behavior is accurate.  It's possible that you are placing an outbound call and there is no caller ID, or that a server in the middle of the call (like Asterisk or FreeSWITCH) is replacing it with the extension.  Alternatively, if you are looking for the local endpoint's caller ID, you might want to check `session.localIdentity.displayName`.

Until this is shown to be a bug in SIP.js, we'd prefer to keep the discussion on the [mailing list](https://groups.google.com/forum/#!forum/sip_js), reserving GitHub for project issues rather than support.  Please create a post there for further help.

Thanks,

-Will

**Comment by LTroya** [comment]
Ah thanks. I will not happen again. 

Btw, I didn't know freeswitch could change the name. I will check the traceSip and the freeswitch.

**Comment by wakamoleguy** [comment]
Yup.  FreeSwitch is a back to back user agent.  When you put it between two WebRTC endpoints, it looks like they are talking to each other, but really FreeSwitch is answering one call and creating another.  The call you receive at Point B is completely different than the one sent from Point A.

**Comment by ferso** [comment]
I resolved this with session.remoteIdentity.uri.user
