### ISSUE TITLE
The guide page for receiving calls includes jsfiddle via http instead of https 

### ISSUE THREAD

**Issue by damoonrashidi** [onsip/SIP.js#402]
https://sipjs.com/guides/receive-call/ includes a jsfiddle with the url `http://jsfiddle.net/OnSIP/vW7Lw/45/embedded/js,html,css,result/`. The browser blocks the request since sipjs.com has been loaded via `https`, this causes the fiddle to not be rendered. Changing the iframe url to use https fixes the issue.

**Comment by james-criscuolo** [comment]
I just pushed an update for this, should be live in a few minutes, thanks!

Also, we do have a [separate repo](https://gitlab.com/onsip/sipjs.com) for the website if you happen to spot anything else. We moved from github to gitlab hosting because github didn't have a clean way to host via https (the way our website is set up anyway).
