### ISSUE TITLE
Using phoneRTC mediahandler

### ISSUE THREAD

**Issue by soulofmischief87** [onsip/SIP.js#439]
Hello,

I am currently having issues using the sipjs mediahandler on a couple of versions of android. At times it appears to function correctly in some versions of android L but not in others. The following error is sent via the js console:

[ERROR:media_stream_dispatcher_host.cc(229)] MSDH: Renderer requested a URL

Monitoring the getUsermedia events on sipjs in relation to failure do not provide additional information. before trying out another library I'd like to know if it is possible to use the phonertc media handler on android? Can anyone provide an example of how the phonertc media handler can be used ?

**Comment by egreenmachine** [comment]
The best example we have will be our [guides](https://sipjs.com/guides/mobile/). In all honesty they are probably outdated, because I cannot remember the last time I touched that stuff. I was going to put a little message saying as much on our website in the next few weeks. If you want more support, lets follow up on the issues of that project.
