### ISSUE TITLE
Requested device not found

### ISSUE THREAD

**Issue by Demitrius** [onsip/SIP.js#515]
Hello

The Demo on website sipjs.com not works for me.

SIPJS old version **0.7.7 works fine**, but 0.8.x and early, even 0.9.2 with error.

PC configuration
- Sound system installed and workable
- Chrome  64.0.3282.167 latest this time
- Permissions allowed (version 0.7.7 works)

**Debug**
```
Sun Feb 18 2018 15:20:49 GMT+0600 | sip.invitecontext.sessionDescriptionHandler | acquiring local media
sip-0.8.3.js:783 Sun Feb 18 2018 15:20:51 GMT+0600 | sip.invitecontext.sessionDescriptionHandler | unable to acquire streams
LoggerFactory.print @ sip-0.8.3.js:783
sip-0.8.3.js:783 DOMException: Requested device not found
LoggerFactory.print @ sip-0.8.3.js:783
sip-0.8.3.js:783 Sun Feb 18 2018 15:20:51 GMT+0600 | sip.inviteclientcontext | closing INVITE session hfr1mfb416tj69kn376h3li5711g46
sip-0.8.3.js:783 Sun Feb 18 2018 15:20:51 GMT+0600 | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
sipjs.com/:1 Uncaught (in promise) DOMException: Requested device not found
```

**Screen:** 
![image](https://user-images.githubusercontent.com/2479194/36350271-f076d6ea-14bf-11e8-9375-945024a54429.png)

**Comment by egreenmachine** [comment]
I tested with Chrome 64 and it appears that you do not allow the page to capture your local media, or the browser is unable to capture the local media device because something else on the system is using it. By default the demo tries to do audio and video so if you do not have a webcam it may not work.

I am going to close this as it is not a problem with SIP.js. If you have further questions please follow up on our [mailing list](https://groups.google.com/forum/#!forum/sip_js)
