### ISSUE TITLE
Hold/Unhold doesn't emit the corresponding events!

### ISSUE THREAD

**Issue by Milad** [onsip/SIP.js#529]
Hello

From `sip.js/src/WebRTC/Simple.js`

```js
  this.session.on('hold', function() {
    this.emit('hold', this.session);
  }.bind(this));
  this.session.on('unhold', function() {
    this.emit('unhold', this.session);
  }.bind(this));
```

So Simple expects the session to emit these two events. But `sip.js/src/Session.js` doesn't emit them!

**Comment by egreenmachine** [comment]
Ah, yeah. We changed this because the session is really unaware of if a session is on hold or not as that is part of the SDP. I am working on a small upgrade to the session description handler to deal with attaching media, let me see if I cannot get something in there to make hold/unhold a bit easier as well.

**Comment by raphaelhovsepyan** [comment]
Any updated on this ?

**Comment by egreenmachine** [comment]
I added an event to the underlying Session Description Handler, but have not yet updated the Simple layer to take advantage of it.

**Comment by gitim** [comment]
Have the same issue, what is the status of this?

**Comment by egreenmachine** [comment]
@gitim I have nothing to update here. I do not think this will make it into the upcoming release.
