### ISSUE TITLE
sip.transport | unable to send message, WebSocket is not open

### ISSUE THREAD

**Issue by thuraucsy** [onsip/SIP.js#558]
Using sipjs together with [pace.min.js](https://raw.githubusercontent.com/HubSpot/pace/v1.0.2/pace.min.js), getting the `WebSocket is not open` warning.

If I put the pace.min.js just before the sip.js,
> 
    <script src="vendors/pace-progress/js/pace.min.js"></script>
    <script src="js/sip-0.7.8.min.js"></script>

I got that warning and cannot make the call using the FreeSWITCH server.

If I put the pace.min.js just after the sip.js,

> 
    <script src="js/sip-0.7.8.min.js"></script>
    <script src="vendors/pace-progress/js/pace.min.js"></script>

no warning and can make the call but no sound.

If I remove pace.min.js, I can make the call and hear the sound normally.

I think it is a pace.min.js error, but want to know why that warning happening.

**Comment by james-criscuolo** [comment]
it looks like that file mucks with websockets in some way, it's hard to tell because the file is minified, but searching it you can see they set the websocket to a variable to do some tracing (at minimum). I'd have to guess when we create a websocket, it returns a wrapped websocket, and we are not prepared for that.

We are currently working on making our transport layer (in the browser case, the websocket) more customizable, similar to the session description handler. Once that work is done, you'd be able to alter our default transport to be prepared for this pace websocket object.

I'm going to close as I don't believe the issue lies with us, but be on the lookout for that transport work soon.
