### ISSUE TITLE
Unhold stops working in Chrome 66

### ISSUE THREAD

**Issue by PavloTV** [onsip/SIP.js#566]
SIP.js 0.7.8 + freeswitch 1.4 + Chrome 67

Another side continue listening "music on hold" even if i pressed unhold in browser.

d09c110e8dbe.js:4051 DOMException: Session error code: ERROR_CONTENT. Session error description: Failed to apply the description for audio: Failed to set SSL role for the transport..
LoggerFactory.print @ d09c110e8dbe.js:4051
LoggerFactory.(anonymous function) @ d09c110e8dbe.js:4052
Logger.(anonymous function) @ d09c110e8dbe.js:4052
createOfferAnswerError @ d09c110e8dbe.js:4536
Promise.catch (async)
createOfferOrAnswer @ d09c110e8dbe.js:4536
streamAdditionSucceeded @ d09c110e8dbe.js:4514
Promise.then (async)
getDescription @ d09c110e8dbe.js:4513
sendReinvite @ d09c110e8dbe.js:4193
unhold @ d09c110e8dbe.js:4188
fn @ VM709:4
callback @ d09c110e8dbe.js:1539
$eval @ d09c110e8dbe.js:1322
$apply @ d09c110e8dbe.js:1323
(anonymous) @ d09c110e8dbe.js:1539
dispatch @ d09c110e8dbe.js:279
elemData.handle @ d09c110e8dbe.js:254

Same issue described by another SIP.js user:
https://groups.google.com/forum/#!topic/discuss-webrtc/cKLDbhGVXQA

**Comment by Xen-Dade** [comment]
I suggest re-investigating this... I'm also having the same problem, I am not using Freeswitch or whatever the original poster is using (the link he referenced to discuss-webrtc says FreeSwitch, and I don't recognize his debug logs)

Broken: Chrome/67.0.3396.87
Working: Chrome/66.0.3359.139

The original poster said it does not work in 66, however, it was not working on my PC in Chrome 66, but I had already ran an update and was waiting for me to restart - it's possible that Chrome activated something new from the new version, with-out needing to restart.

What I've noticed, is that my Audio element in both Chrome/67 and 66:

    Before hold (when audio is bridged):
                audioElement.srcObject.getTracks() === [ MediaStreamTrack ]
                audioElement.srcObject.active === true
                audioElement.paused === false

    After putting on hold, and taking off of hold
                audioElement.srcObject.getTracks() === []
                audioElement.srcObject.active === false
                audioElement.paused === false

and to fix the audio, I can do this:
                audioElement.srcObject = inviteClientContextInstance.mediaHandler.getRemoteStreams()[0];
                audioElement.play()

Before the audioElement.play, after setting audioElement.srcObject, audioElement.paused === true



Notice I didn't mention a difference between versions - the only difference between versions, is that Chrome 67 doesn't work, and Chrome 66 does.

In both Chrome 66 and Chrome 67, the above assertions are true, although, in 66, it does not affect audio playback

I suspect Chrome 67 fixed a bug that previously allowed it to be held open regardless of the MediaStream instance being different, and that this has activated previously unknown bug in sip.js.


Hoooweever.... I'm using a modified, very old version of sip.js :)  so maybe the above collaborator is talking about something entirely different.

Have fun!

**Comment by seanbright** [comment]
> Hoooweever.... I'm using a modified, very old version of sip.js :) so maybe the above collaborator is talking about something entirely different.

Are you able to reproduce this issue with the latest, unmodified sip.js? That would potentially be more useful.

**Comment by Xen-Dade** [comment]
No, I've no interest in doing so, I spent enough time working through the problem yesterday under 'priority 1' status.  I found this thread before finding the problem/solution/workaround, and figured I'd let you guys know, since it appears to be brushed off (though if so, due to an inadequate description).  Maybe you're right & all of our customers just happened to have had the same problem as the original poster around the same Chrome release.

I apologize for the directness, but I figure it's better than not responding.

**Comment by PavloTV** [comment]
I did not test with SIP.js 0.8, but with freeswitch 1.6.20 this issue is not reproduced.

**Comment by seanbright** [comment]
@Xen-Dade no problem. On other OSS projects I have worked on, if someone reported a problem with an old release that they'd modified, we would ask them to reproduce with the unmodified latest version. Without doing that we'd have no way to know if it was the modifications themselves that were breaking things, line numbers in logs and diffs wouldn't make up, etc. If things are working for you now, that's great.

@PavloTV so to be clear, upgrading from FreeSWITCH 1.4 to 1.6.20 resolved this issue for you?

**Comment by egreenmachine** [comment]
Hi All, I would like to address this as thoroughly as possibly. 

First off, while there were hold and unhold functions in 0.7.X, we have never claimed support for hold/unhold in that version of SIP.js. In fact, I fully expect that hold/unhold is broken in 0.7.X. 0.8.X saw a major refactor of the SDP handling code within SIP.js and the primary goal of this was to get a solid base to support hold/unhold.

Secondly, @seanbright is correct we cannot support custom SIP.js code. If there is an issue with SIP.js any custom code needs to be ruled out as the problem. We (the maintainers, OnSIP) use SIP.js with a large customer base and our SIP compliant platform. We always recommend using the latest version because it is what we use and where we fix issues. I understand that recently we have made a number of API breaking changes, but this is in an effort to build the best library possible. In the end the updates should really be minimal and will pay off in the future.

Thirdly, while everyone in this thread apparently had a hold/unhold issue it was never clear what the issue is. Full logs, or instructions on how to reproduce are needed to debug the issue. I stated that in my initial response. Additionally, I had previously seen that error when testing an older version of Freeswitch which was not setting the role correctly which is why I pointed towards the media gateway in my initial response. As stated by @PavloTV it appears updating Freeswitch resolved his issue and it was not a SIP.js issue. It is easy to blame SIP.js when a browser updates, but most of time we do not have control over the updates to the WebRTC layer. 

Lastly, we would like SIP.js to be a collaborative inclusive environment. I find it tough to claim that this issue was brushed off. I quickly responded and gave several recommendations and asked for several pieces of information to provide a more thorough solution. The initial comment from @Xen-Dade after me appears to have ignored my comment and further comments are openly hostile towards the community. This behavior is unacceptable and we are hoping that in the future you can use this as a lesson to be a bit kinder and understanding towards people freely helping each other on the internet. Since the initial issue in this thread appears to be resolved, I am going to close this.

Thank you,
-Eric Green

**Comment by james-criscuolo** [comment]
@PavloTV We have a different use case I'm sure, but we've been using Freeswitch 1.6.14 in a production environment for over a year now, if that is at all helpful.
