### ISSUE TITLE
Cannot response incoming call with SIP.js 0.11.2

### ISSUE THREAD

**Issue by aubalde** [onsip/SIP.js#603]
Hi all,

I'm validating the new library 0.11.2 into my environment, but I can't response an incoming call.

I've the following error after a few seconds:

============================================================
sip-0.11.2.js:4665 Uncaught TypeError: Cannot read property 'remote_target' of undefined
    at InviteServerContext.sendRequest (sip-0.11.2.js:4665)
    at sip-0.11.2.js:5148
============================================================

Any idea?

Thanks

**Comment by egreenmachine** [comment]
Please follow the template that you deleted. I have included it below for reference.

**Describe the bug**
A clear and concise description of what the bug is.

**Logs**
Please include a [gist](https://gist.github.com/) or attached file with full logs. If this is not included, the first response will likely be requesting them.

**To Reproduce (if possible)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**
Add any other context about the problem here.
