### ISSUE TITLE
session.cancel() then ua.stop() real quick sends multiple cancel

### ISSUE THREAD

**Issue by andrewvmail** [onsip/SIP.js#618]
Hello sipjs team,

Not sure if this is a bug or its fine. 

When I session.cancel() then ua.stop() real quick sipjjs sends multiple cancel. my ua.stop code is located inside session.on('cancel') event handler. (sip.js@0.11.3)

My work around is i just do ua.stop() and that sends out the cancel and stop the ua

https://github.com/davehorton/drachtio-server/issues/54

**Comment by egreenmachine** [comment]
Can you provide a [gist](https://gist.github.com/) with logs that have [traceSip](https://sipjs.com/api/0.11.0/ws_transport_configuration_parameters/#tracesip) turned on? 

The most likely cause of this is because the event emission is happening before the session is cleaned up. So by calling `UA.stop` the UA then tries to clean up the session, which results in a cancel being sent. If I can see where this is happening I can get it resolved for our next release.

**Comment by andrewvmail** [comment]
Okay cool! will get you the gist over the weekend

**Comment by andrewvmail** [comment]
gist here https://gist.github.com/andrewvmail/3f1ca4c9659d38ca18cf08b80e951f63
