### ISSUE TITLE
Chrome 70 peerConnection.getSenders() is empty on incoming call

### ISSUE THREAD

**Issue by solispauwels** [onsip/SIP.js#629]
I am unable to get local tracks using getSenders when receive incoming calls on Chrome Version 70.0.3538.77 (Build officiel) (64 bits linux). In Outgoing calls it works correctly.

In Firefox  63.0 (64 bits linux) it works as expected both in incoming and outgoing.
```
SIP/2.0 200 OK
Via: SIP/2.0/WS 172.16.10.37:5060;branch=z9hG4bK41cd3790
To: <sip:49gev5b8@cbnpp90drcj9.invalid;transport=ws>;tag=kkeho693qs
From: "Jerrylee Croxall" <sip:3004@172.16.10.37>;tag=as2dbd6f4f
Call-ID: 4a26df3f5e45ba7f26d6b6070bd73a8b@172.16.10.37:5060
CSeq: 102 INVITE
Contact: <sip:49gev5b8@cbnpp90drcj9.invalid;transport=ws>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound
User-Agent: XXXX
Content-Type: application/sdp
Content-Length: 935
v=0
o=- 1673124817333793893 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS YFw129DbO6h9BukmvGDXFE4l547W3C34GjUk
m=audio 39831 RTP/SAVPF 8 107 101
c=IN IP4 172.16.40.75
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:349827926 1 udp 2122260223 172.16.40.75 39831 typ host generation 0 network-id 1
a=ice-ufrag:f6yp
a=ice-pwd:P+QW/Myk/IE/P98BdhdSHdkh
a=ice-options:trickle
a=fingerprint:sha-256 6B:60:09:3D:39:0C:9C:65:7B:01:AC:C2:4F:5C:0D:82:F0:C4:DD:95:97:D9:06:DF:4D:53:AD:DF:20:82:F0:C6
a=setup:active
a=mid:audio
a=sendrecv
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:107 opus/48000/2
a=fmtp:107 minptime=10;useinbandfec=1
a=rtpmap:101 telephone-event/8000
a=ssrc:1899133475 cname:6GWT8ARjPcbR/um9
a=ssrc:1899133475 msid:YFw129DbO6h9BukmvGDXFE4l547W3C34GjUk d466a1ae-fc38-42c8-895d-c50050a491fa
a=ssrc:1899133475 mslabel:YFw129DbO6h9BukmvGDXFE4l547W3C34GjUk
a=ssrc:1899133475 label:d466a1ae-fc38-42c8-895d-c50050a491fa
```

**Comment by egreenmachine** [comment]
Not enough information and questions like this should be on our [mailing list](https://groups.google.com/forum/#!forum/sip_js).

**Comment by solispauwels** [comment]
what do you need as more information. seems that is not a chrome fault cause I can correct this by adding a setTimeout of 500ms to the addTrack event. is this event fired too soon in chrome 70?

**Comment by egreenmachine** [comment]
Heres our template for a bug report. It came up when you opened this on Github.

**Describe the bug**
A clear and concise description of what the bug is.

**Logs**
Please include a [gist](https://gist.github.com/) or attached file with full logs. If this is not included, the first response will likely be requesting them.

**To Reproduce (if possible)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**
Add any other context about the problem here.


Here is from our [FAQ](https://sipjs.com/faq/):
My SIP.js application isn’t working! Where do I get help?
The best way to get help is through our Google Group mailing list. Make sure that you include logs with traceSip enabled in a gist. The Github issue tracker is reserved for bugs within the library.

Here is from our [mailing list](https://groups.google.com/forum/#!forum/sip_js):
If you have a question about why SIP.js isn't working for you, please enable traceSip in your UA config and include in your post a link to a gist containing the JS console output. See also: How to Report Bugs Effectively

Also from our [mailing list](https://groups.google.com/forum/#!topic/sip_js/_9tyhE8-xPc):
If you have a question about why something is not working you will need to provide full logs with traceSip enabled in a gist. If you do not do this your question will be ignored by the maintainers.

Please also take a moment to review our FAQ which contains information on what we will support.

Thanks Everyone!

-----------------------

Let me know which of these is unclear. I am trying to improve the way which people report bugs to us.

**Comment by miladmeidanshahi** [comment]
same problem

**Comment by james-criscuolo** [comment]
```
    handleSIPSessionEvents CallCard.vue:726 handleSIPSessionEvents CallCard.vue:725 emit events.js:146 trackAdded SessionDescriptionHandlerObserver.js:16 acquire SessionDescriptionHandler.js:488 
    Mon Feb 18 2019 13:07:59 | sip.inviteservercontext | unable to acquire streams LoggerFactory.js:88
TypeError: "Argument 1 of MediaStream.addTrack is not an object."
```
This is an issue in your code.

**Comment by miladmeidanshahi** [comment]
I don't think so. the track in getSenders() is null because of that I can't
add track.

**Comment by james-criscuolo** [comment]
The part of the log that would probably lead to this is where it does not obtain your streams correctly: 
```
Mon Feb 18 2019 13:07:59 | sip.invitecontext.sessionDescriptionHandler | unable to acquire streams
```
Are you using the default session description handler? It looks like right when the peer connection is made, it emits track added, which doesn't add up, and then it attempts to getUserMedia, and fails. Outside of all of that, I would check the permissions on your page to make sure you can successfully call getUserMedia.

**Comment by miladmeidanshahi** [comment]
yes I'm using session description handler and the interesting point is that without setting local stream it's works

**Comment by james-criscuolo** [comment]
Putting a conditional before the track is used (`if (sender.track) {`) would probably be ok here.

**Comment by solispauwels** [comment]
In my case, sipjs gets correctly the media stream but the event is simply fired too soon with an empty value, so maybe try to add a delay to it as i said previously here, I left that delay in the code that I work  because I have no time to waste reporting that bug with the template here.

**Comment by miladmeidanshahi** [comment]
yes, I do that but why it's work without local stream? before sip 0.13.0 we have to set local stream

**Comment by solispauwels** [comment]
In my case I have to do something like this (in a simplified way):

```js
function trackAddedHandler () {
  const { peerConnection } = sipJsSession.sessionDescriptionHandler

  if (peerConnection) {
    remote = peerConnection.getReceivers()
    setTimeout(() => { local = peerConnection.getSenders() }, 500)
  }
}
````

**Comment by james-criscuolo** [comment]
It seems to be adding a dtmfSender before we are telling it to (we only add it in `sendDtmf`), which then causes an emission. I would be tempted to say that this is new in Chrome, instead of something wrong with SIP.js, only because given you have a sender just for DTMF, that error would end up occurring on every pass to this function. If this is the case, you'd still need to update your code as I've described, and we can update our guide to prevent for this.

**Comment by solispauwels** [comment]
In my case the trackAddedHandler is called only once, nothing to do about a dtmf, who talk abour a dtmf? why you propose to use an "if" to check if sender have something? The getSenders is returning an emty value if I do not use a delay... Then yes the trackAddedHandler is called again only in the case I do a hold/unhold or a renegotiation.

**Comment by james-criscuolo** [comment]
Here's the dtmf sender you posted earlier: 
```
pc.getSenders()[0]
RTCRtpSender {track: null, dtmf: RTCDTMFSender}
```
Also please update to 0.13.5 and post new (complete) logs.

**Comment by solispauwels** [comment]
Me?

**Comment by james-criscuolo** [comment]
Sorry, did not realize I was talking to two people. I do not think the timeout you are using would work in cases where the getUserMedia does not automatically complete (first time users, most firefox users) and recommend the conditional route. But my responses have been in regards to @miladmeidanshahi for the most part.

**Comment by miladmeidanshahi** [comment]
actually, this code is for the latest version 0.13.5
```
pc.getSenders()[0]
RTCRtpSender {track: null, dtmf: RTCDTMFSender}
```
