### ISSUE TITLE
Add a way to create InviteClientContext asynchronously, then send the INVITE

### ISSUE THREAD

**Issue by nud** [onsip/SIP.js#636]
**Is your feature request related to a problem? Please describe.**

We have some code where we create an `InviteClientContext` then wrap it into some object that contains more information. That object will be registering some handlers against the session. The problem is that we need to instantiate this object asynchronously, but SIP.js would send the INVITE in the next tick after the `InviteClientContext` is instantiated.

For us, this causes a race condition, as SIP.js might try to trigger event handlers before we got a chance to register them.

**Describe the solution you'd like**

Any officially supported way to instantiate the `InviteClientContext` then trigger its `invite()` method later. Possible solutions are:

- `UA.invite()` would accept a callback that returns a `Promise`, and calls `session.invite()` when the `Promise` is resolved. If no `Promise` is passed, then it invites immediately.
- `UA.invite()` takes some option that prevents calling `session.invite()` so we can call it later.

**Describe alternatives you've considered**

Right now, our workaround is to "cut and paste" `UA.invite()` in such a way that we can trigger `InviteServerContext.invite()` at the moment we like.

**Additional context**

**Comment by john-e-riordan** [comment]
It does appear we have an interface deficiency with regard to the inherent race condition implicit in...
```
var ua = new UA(...);
var inviteClientContext = ua.invite(..); // send my INVITE
inviteClientContext.on(...); // register my handler(s)
```

That's undeniably "closing the stable door after the horse has bolted" (not to mention arguably  confusing for the API consumer). And it simply fails if the caller yields...
```
var ua = new UA(...);
var inviteClientContext = ua.invite(..); // send my INVITE
Promise.resolve().then(() => inviteClientContext.on(...)); // I yield, then register handler(s)
// At this point I may have missed events
```

The non-yield case only works today because of the following "implementation choice" in `InviteClientContext.invite()`...
```
// This should allow the function to return so that listeners can be set up for these events
Promise.resolve().then(() => {
  if (this.inviteWithoutSdp) {
```

These "stable door" and "caller yields" interface issues also exists for the other "context factory" instance methods of `UA` (`subscribe`, etc), so we have a consistency issue to be concerned with. As a bit of a side note, #583 is potentially exacerbated by doing anything async like this currently.

Anyway, for what is is worth, while I believe the solutions proposed by @nud would work, I'd thought I'd document another approach to solving the issue. We could "add a step", which in general looks something like this...
```
// It's perhaps worth noting that this example works with zero
// changes to the current library (0.13.x I believe, I haven't tried it,
// it is NOT officially supported/documented, and as such will likely
// break in future, so likely a mistake to mention it at all, etc etc)
var ua = new UA();
var icc = new InviteClientContext(ua, ...);
// ... async time passes ...
// ... setup handlers ...
icc.invite();
```

This eliminates the "stable door" and the "caller yields" API issues, but introduces an additional way to invite, subscribe, etc. Adding a step also arguably introduces a hurdle, confusion, room for error, etc

### Out of Scope...

The downsides of adding a step are, I think it is safe to say, non-trivial. But that could perhaps be offset up introducing a new API (and thus I'm "out of scope"). But for giggles...
```
// TLDR; This is fantasy code (don't try this at home, it doesn't run).

// UserAgent
const userAgent = new UserAgent(...);
userAgent.on(...); // or userAgent.delegate = {...};

// Invite UAC
const invite = new OutgoingInviteRequest(userAgent, ...);
invite.on(...); // or invite.delegate = {...};
invite.send()
  .then((session: Session) => /* Outgoing INVITE accepted, have a new session. */ )
  .catch((failureReason) => /* Outgoing INVITE send failed, have a reason. */ );

// Invite UAS
onIncomingInvite((invite: IncomingInviteRequest) => {
  invite.on(...); // or invite.delegate = {...};
  invite.accept()
    .then((session: Session) => /* Incoming INVITE accepted, have a new session. */ )
    .catch((error) => /* Incoming INVITE accept failed, have an error */ );
};

```

**Comment by john-e-riordan** [comment]
In the new API, you can construct an `Inviter` and at some point in the future call `Inviter.invite()`.
