### ISSUE TITLE
Cannot read property 'UA' of undefined

### ISSUE THREAD

**Issue by miladmeidanshahi** [onsip/SIP.js#644]
**Describe the bug**
After upgrade to sip 0.13.0 `new SIP.UA`, It doesn't work anymore.

**Logs**
TypeError: Cannot read property 'UA' of undefined

**To Reproduce (if possible)**
1. import SIP from 'sip.js'
2. try to create UA

**Expected behavior**
import sip after upgrade to 0.13.0 not work and nothing imported but in version 0.12.0 works correctly.

**Observed behavior**
`import SIP from 'sip.js'` It does't import any thing, if you `console.log(SIP)` you got `undefined`

**Environment Information**
 - Google chrome latest

**Comment by miladmeidanshahi** [comment]
@egreenmachine

**Comment by james-criscuolo** [comment]
Can you try `import * as SIP from sip.js;` or `import { UA } from 'sip.js';`? I believe the former is how we used to recommend using import, and the latter is now doable but the former still works.

**Comment by miladmeidanshahi** [comment]
It works, but why it's has changed ?

**Comment by james-criscuolo** [comment]
Long story short, we never claimed support for import in the way you were doing it, so when the update occurred I did not try to make that import work.

Long term we'd prefer people not importing a monolithic object, as it would get in the way of treeshaking during bundling. When the update was made to using ES modules instead of an IIFE (0.13.0), we did not make a default export, which would've been how you were importing. Our recommended import was `import * as SIP from 'sip.js';`, and now that is still works, but purely for backwards compatibility. Going forward, we recommend `import { UA } from 'sip.js'`;
