### ISSUE TITLE
registrationFailed is not called on net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by hansifer** [onsip/SIP.js#651]
**Describe the bug**
When instantiating a new SIP.UA and websocket connetion fails with `failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED`, `registrationFailed` event never fires.

**Logs**
[sip-log.txt](https://github.com/onsip/SIP.js/files/2873395/sip-log.txt)

**To Reproduce (some values obscured with `foo` and `bar`)**
```javascript
const config = {
  transportOptions: {
    wsServers: [
      'wss://foo.net:5065'
    ],
    traceSip: true
  },
  uri: 'foo@bar.com',
  password: 'foo',
  rel100: SIP.C.supported.SUPPORTED,
  userAgentString: 'foo',
  register: true,
  hackViaTcp: true,
  log: {
    level: 'debug'
  },
  sessionDescriptionHandlerFactoryOptions: {
    peerConnectionOptions: {
      rtcConfiguration: {
        iceServers: [
          { urls: 'stun:stun.1.google.com:19302' },
          {
            urls: 'turn:foo:443?transport=tcp',
            username: 'websip',
            credential: 'websip'
          }
        ]
      }
    }
  }
};

const ua = new SIP.UA(config);
ua.on('registrationFailed', handleRegistrationFailed);

function handleRegistrationFailed() {
  console.error('REGISTRATION FAILED'); // never called
}
```

**Expected behavior**
`registrationFailed` event should be fired after websocket connection retries have been exhausted.

**Observed behavior**
`registrationFailed` event never fires after websocket connection fails consistently.

**Environment Information**
This is an Electron 3 (Chrome 66) app using sip.js v0.11.6. Same behavior observed with sip.js v0.13.5.

**Comment by hansifer** [comment]
Some additional detail: listening to transport events I also observed the following:

```
ua.transport.on('transportError', handleTransportError);
ua.transport.on('disconnected', handleDisconnected);

function handleTransportError(e) {
  console.error('TRANSPORT ERROR', e); // gets called 2x per try (with e === undefined)
}
function handleDisconnected(e) {
  console.log('DISCONNECTED', e);  // gets called 1x per try with e of {code: 1006, reason: ""}
}
```

**Comment by egreenmachine** [comment]
The transport events are correct. Are you seeing any inconsistency there?

The registration events I am not certain about here. The reason the event is not getting fired is because the registration is never even attempted. The reason the registration is not attempted is because the transport is never connected. So essentially what you are getting at here is that `registrationFailed` should be fired even though a registration was never attempted? From that technical standpoint it seems wrong. You should ensure that the application is connected then listen for registration events.

From a less technical perspective I can understand why you may just want to listen for a single `registrationFailed` event. You don't care that the transport never connected, you simply care if the end result a successful registration or failed registration happened. The intermediate steps you do not really care about. 

I am not inclined to start changing behavior here without taking a deep dive into registrations.

**Comment by hansifer** [comment]
I agree the transport events are consistent. Just adding observational details.

Yes, I was hoping that since sip.js is already abstracting and providing facilities for establishing connections, that some failure event would exist at the same level of abstraction. Since that is not the case, it seems the app needs to listen to events at the transport level and count the `transportError` events separately. Setting the failure threshold accordingly with this approach is somewhat problematic because:

1) It requires the application to know how many times sip.js will retry the connection. I know this can be set explicitly, but it seems cleaner to not have to coordinate this.

2) It requires the application to know that exactly 2 `transportError` events will fire for each failed connection attempt. This is just based on my recent observations. I don't know that it's sensible to expect this behavior to be consistent across environments and time.

It seems that sip.js is best qualified to know definitively when its retry attempts have been exhausted. From the perspective of the API consumer, I believe it's reasonable for an event to exist to notify that a call to `.register()` did not in fact ultimately result in a registered state, regardless of the reason.

Thanks for your response and your further consideration.

**Comment by john-e-riordan** [comment]
With the new API, you can now
- optionally pass a delegate to a call to `Registerer.register()` to obtain the ultimate result of the associated register
- unambiguously monitor the registration state changes

**Comment by james-criscuolo** [comment]
0.16.0 is now released, which is new API only, and new API has decoupled these, so it's now a non-issue, closing.
