### ISSUE TITLE
No events emitted for network error

### ISSUE THREAD

**Issue by seanplwong** [onsip/SIP.js#659]
**Describe the bug**
During lost of network connectivity for an accepted call session, there is no event fired to inform upper layer about the network error. `failed` by design will not be fired after `accepted`, but there is no `terminated` event, to be notified about the network error.
As a result, call disconnected due to network error cannot be updated in UI.

**Logs**
https://gist.github.com/seanplwong/0397f2e0dc57f4a1b8761d9e66070e65

**To Reproduce (if possible)**
Steps to reproduce the behaviour:
1. Make a call
2. Answer the call
3. Disconnect after `accepted` event

**Expected behavior**
client can be informed about network error.

**Observed behavior**
so far neither `failed`, `bye` nor `terminated` is fired

**Environment Information**
NA

**Additional context**
NA

**Comment by egreenmachine** [comment]
It looks as if the default transport is emitting an error, but the UA is eating it. @mi-ruan is looking at this code currently and can get this case resolved.

**Comment by seanplwong** [comment]
I have a few questions for Transport, looks like it will emit `transportError` for every error received from `WebSocket`, but it will try to reconnect as well. should it be considered error only after reconnect failed? or maybe the call is already dropped and the session cannot be recovered?

**Comment by egreenmachine** [comment]
No. The error has happened and we want to report on that. There should be separate events and state changes of the Transport to indicate that it has tried to reconnect or all of the reconnections have failed. 

If you need different behavior than what is provided the Transport is very easy to override.

**Comment by egreenmachine** [comment]
@seanplwong We looked into this and as it stands it looks like SIP.js is correct. The session is not marked as `failed` or `terminated` because the websocket has dropped. You can listen for events on the Transport itself to determine the transport state and then attempt to kill the sessions yourself. At that point they should then  mark it as failed.

In terms of the UA eating the event, it is not the UA's responsibility to emit events on behalf of the Transport. 

I am closing this issue, but if you have any other questions or concerns feel free to continue this thread.
