### ISSUE TITLE
SessionDescriptionHandler : missing events + peerConnection typings

### ISSUE THREAD

**Issue by jlaine** [onsip/SIP.js#681]
**Describe the bug**
SIP.js recently gained TypeScript types, which is fantastic! Unfortunately some types are missing on SessionDescriptionHandler:

- the `on()` method (from EventEmitter) is not available

- the `peerConnection` attribute is not available

**Logs**
`Property 'on' does not exist on type 'SessionDescriptionHandler'.`

`Property 'peerConnection' does not exist on type 'SessionDescriptionHandler'.`

**Additional context**
I'd be happy to submit a PR but I'm not entirely sure how to proceed : if memory serves the "SessionDescriptionHandler" could potentially be subclasses for usecases other than WebRTC, so I'm not sure whether we want to add the typings directly for SDH or whether they would only apply to `SIP.Web.SessionDescriptionHandler` ?

**Comment by jlaine** [comment]
Actually a closer look shows that `SIP.Web.SessionDescriptionHandler` *does* have these attributes, so I suppose it's a matter of casting the SDH as in:

```
Session.on('SessionDescriptionHandler-created', (sessionDescriptionHandler: SIP.Web.SessionDescriptionHandler) => {
    // do something with SDH
});
```

Feel free to close this issue if you feel this is the right way to go.

**Comment by egreenmachine** [comment]
Hi Jeremy, good to see you back!

You are correct that the base `SessionDescriptionHandler` does not have `on` or `peerConnection` exposed. This is so that you could implement it for other uses outside of WebRTC. The Web SessionDescriptionHandler does expose the peerConnection https://github.com/onsip/SIP.js/blob/master/src/Web/SessionDescriptionHandler.ts#L52. 

The `on()` event emissions are also typed for the Web SessionDescriptionHandler https://github.com/onsip/SIP.js/blob/master/src/Web/SessionDescriptionHandler.ts#L362.

The core SIP.js library requires that any SDH follow only the interface defined at https://github.com/onsip/SIP.js/blob/master/src/session-description-handler.ts. Since the SDH can be overridden by the user and it is only required to adhere to the interface the type that SIP.js can return is only guaranteed to be the interface. We cannot guarantee it to be anything else. In this instance, the user is probably smarter than the typescript compiler. You know what SDH you are using, so you can cast it to that type.

I am open to improving this if possible, but we do not know of a better way at the moment. I am going to close this, but feel free to continue to discuss or re-open if it does not cover what you were asking.

**Comment by hamzalps** [comment]
> Hi Jeremy, good to see you back!
> 
> You are correct that the base `SessionDescriptionHandler` does not have `on` or `peerConnection` exposed. This is so that you could implement it for other uses outside of WebRTC. The Web SessionDescriptionHandler does expose the peerConnection https://github.com/onsip/SIP.js/blob/master/src/Web/SessionDescriptionHandler.ts#L52.
> 
> The `on()` event emissions are also typed for the Web SessionDescriptionHandler https://github.com/onsip/SIP.js/blob/master/src/Web/SessionDescriptionHandler.ts#L362.
> 
> The core SIP.js library requires that any SDH follow only the interface defined at https://github.com/onsip/SIP.js/blob/master/src/session-description-handler.ts. Since the SDH can be overridden by the user and it is only required to adhere to the interface the type that SIP.js can return is only guaranteed to be the interface. We cannot guarantee it to be anything else. In this instance, the user is probably smarter than the typescript compiler. You know what SDH you are using, so you can cast it to that type.
> 
> I am open to improving this if possible, but we do not know of a better way at the moment. I am going to close this, but feel free to continue to discuss or re-open if it does not cover what you were asking.

The Dumb one has arrived(me), so what's the solution in simple terms?
