### ISSUE TITLE
Version 0.16.1 fails

### ISSUE THREAD

**Issue by artem7902** [onsip/SIP.js#819]
**Describe the bug**
Hello contributors, I have an electron app with TypeScript. I've updated the package to the 0.16.1 and have the following error during my dev run. With 0.16.0 it starts without error.

**Logs**
![image](https://user-images.githubusercontent.com/26010756/83747720-b5cb5500-a669-11ea-85c8-ecf7ac706e93.png)

**To Reproduce (if possible)**
1. Install the new package
2. Run the app

Thanks a lot for your work and for further replies ;)

**Comment by james-criscuolo** [comment]
This is because we are now an es6 module, You can read more about it here: https://github.com/onsip/SIP.js/blob/master/docs/compatibility.md

The short of it is, if your build target is es5, you need to use babel, or babel-loader in webpack, to make this and other es modules work. If you do not know why you are targeting es5, you should update that to at least es6.

I'm going to leave this open to make sure the suggested change or workaround will work, as we anticipated people have this issue, but expect the above to work.

**Comment by artem7902** [comment]
@james-criscuolo  Thanks for your reply. But I actually use babel-loader with '@babel/preset-env' and '@babel/preset-typescript'. But it doesn't work.        

```
rules: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
            },
          },
        },
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
            },
          },
        },
      ]
```

**Comment by james-criscuolo** [comment]
You are excluding all node_modules, you probably want a line added like
```
		  include: /node_modules\/sip\.js/,
```

**Comment by james-criscuolo** [comment]
Sorry, other thing i noticed, `module` should not be `CommonJs`. Switching that to `ESNext` should fix, instead of messing with `babel-loader". I'm sure there are other values for `module` that would work, I just know `esNext` will.

**Comment by james-criscuolo** [comment]
Going to close as I anticipate one of the above solutions fixed this.
