### ISSUE TITLE
Attended Transfer - REFER - Dialog undefined

### ISSUE THREAD

**Issue by ZeljkoBenovic** [onsip/SIP.js#874]
Hi,

It looks like there is a bug on attended transfer API.
Unattended Transfer works just fine.
When I call refer method on an existing session, and pass it a new session ( Inviter ) instead of URI, it throws an error :
`ERROR Error: Dialog undefined.`
Console log of the new session shows that the dialog is undefined.
I was following the sipjs.com Guides about the Call Transfer.
It seams pretty straightforward but still the Attended Transfer does not work.

So, basically this is the issue ( example from sipjs.com guides ):
```
const replacementSession = newInviter(userAgent, UserAgent.makeURI("sip:bob@example.com")); ( btw there is a typo on the web site, it should be new Inviter )
session.refer(replacementSession);

The error is that :
replacementSession.dialog === undefined --- so now session.refer() doesn't work as it needs this property and 
```

For some reason the dialog property on new Inviter instantiated object is not set .

**Comment by eugenesyuk** [comment]
Had to deal with the same problem. Basically, session dialog property is being set when session becomes established, it means that you have to make invite first and on session established state make a refer.

**Comment by eugenesyuk** [comment]
Attended transfer flow description https://tools.ietf.org/html/rfc5589#page-24. SIP.js just doesn't handle whole process, you have to play around on your own a little bit  =)

**Comment by john-e-riordan** [comment]
Correct - only blind transfers and attended transfers to established sessions are supported. Semi-attended transfers where the target is ringing and has not yet answered are not supported.

A more informative error message will go out in the next release, but check to see if the target session is in state "Established" before calling refer for an attended transfer. If the session is not established and you wish to proceed you can fallback to a blind transfer using the targets URI instead of passing in the Session.

**Comment by Dilshan-Dekumpitiya** [comment]
While transfer using 0.21.2-sip.min.js I got same issue..Any resolution ?
