### ISSUE TITLE
Out of dialog REFER requests

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#89]
It is possible to receive REFER requests as initial, out-of-dialog requests.  Some phone systems use this mechanism for third party call control behavior of some kind.  At the moment, SIP.js will reject the request with `405 Method Not Allowed`.

I believe this would be possible to implement similarly to our MESSAGE handling.  That is, we add a `ua.on('refer', callback)` event.  If the application defines such a callback, call it.  Otherwise, reject with 405.

As for the actual behavior of the REFER, check [RFC 3515](https://tools.ietf.org/html/rfc3515).  It should be similar to in-dialog REFER, although we probably don't want to provide the convenience method.  Doing so would encourage applications to implement this behavior without prompting the user.  Per the RFC, the user SHOULD be prompted for permission.

**Comment by egreenmachine** [comment]
Can you try out #459? I think that I have addressed this issue there. You will need to enable `allowOutOfDialogRefer` on the UA. Any user that uses this feature should implement some security to validate the out of dialog refer, otherwise it could be used maliciously.

* Due to the age of this issue, if we do not hear any feedback on this we will close it once we merge the pull request.
