### ISSUE TITLE
Interop with FreeSWITCH's "NDLB-connectile-dysfunction"

### ISSUE THREAD

**Issue by Destreyf** [onsip/SIP.js#90]
When trying to place a call to the soft client via WSS, FreeSWITCH reports "NORMAL_TEMPORARY_FAILURE" 

the lines look like this
68c1c893-62c2-4035-823c-c19b90232960 2014-08-17 10:47:50.066431 [NOTICE] sofia.c:7286 Hangup sofia/internal/sip:ck4vtuei@74.211.93.8:57566 [CS_CONSUME_MEDIA] [NORMAL_TEMPORARY_FAILURE]

I can call a regular sip client just fine, and even using SipML5 (which we had been previously using) works without issues.

This is also affecting presence subscriptions (no messages are seen).

Changing over to WS, calls and presence both start working.

I would attach JS SIP Traces and wiresharks, but JS SIP traces never show a call attempt, and because its HTTPS/WSS wire shark is pretty much useless (unless someone knows how to decrypt the streams).

What testing has been done against WSS, am i missing something that could potentially be killing me?  

Unfortunately using WS is not really an option because you cannot connect to WS from HTTPS due to security restrictions.

Outbound calling works flawlessly on both WS and WSS.

In the mean time, i will start investigating the code to see if i can generate any sort of output.

**Comment by wakamoleguy** [comment]
> We will be resuming development on our soft client in December, if during that time we find a resolution on either end i will update this issue...
Has anything come out of that?

**Comment by Destreyf** [comment]
@wakamoleguy 

We had to push development off a little bit, we've resumed it just recently but we don't have any time slated for looking into this.

I did some very basic tests and didn't get anywhere.  We want to address this once we have some more time available as we're going to be advertising it as highly secure, and it'll be our main push for people who don't want to buy hardware phones.

**Comment by emiliorcueto** [comment]
This interests me as well and I've started looking into it.

Very preliminary dive points to the default `case` in the switch statement checking the `method` var within the `US.prototype.receiveRequest` method.

I'll be digging in at some point this week and let you know what I find

**Comment by davidnamango** [comment]
For anyone still experiences issues with this setting in FreeSWITCH as I was, if you set 

> hackWssInTransport: true

 in your ua configuration then you will be able to successfully make inbound and outbound calls with wss.

This workaround does make it so you cannot make inbound calls (calls to the soft client) using regular ws however. Which is the opposite of the original issue of not being able to make inbound calls with wss. As wss is more secure anyways I see this as an okay tradeoff because you can just always enforce wss.

I've done minimal testing on this, but I will report back if I find any issues with this.

**Comment by egreenmachine** [comment]
My conclusion at the moment is that we are not compatible with FreeSWITCH NDLB (no device left behind). This is turned on or off based on the individual user registering and should be off by default. The purpose of the option in FreeSWITCH is to support devices that have bad behavior with certain headers and params or for networks with NAT problems etc. Since SIP.js is establishing a socket based connection to FreeSWITCH and SIP.js correctly deals with SIP headers no NDLB options should be required. To make SIP.js behave correctly NDLB would be a backwards move. I am going to close this issue, but if there are more questions definitely feel free to continue this thread.
