### ISSUE TITLE
how  to use sip.min.js directly in browser html 

### ISSUE THREAD

**Issue by lidp888** [onsip/SIP.js#957]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).

the default released sip.min.js can not be used directly in html javascript tag, what should we do to achive this ? it seems import js lib to node module work  , but some sdk users want use it in html directly, maybe need some work in sdk build script ?  need your help, thanks.

**Comment by james-criscuolo** [comment]
We removed the distributables from npm in [our 0.17.0 release](https://github.com/onsip/SIP.js/releases/tag/0.17.0), but you can still download them (or link directly to the github URL) and use them that way. We use the distributable in this fashion on sipjs.com, so you can view it there. I do not believe we've touched our build mechanisms since then, so it should still work as expected on 0.20.0, although on our site we have 0.17.1.
