### ISSUE TITLE
sessionDescriptionHandler.remoteMediaStream.getVideoTracks() not fully populated

### ISSUE THREAD

**Issue by InnovateAsterisk** [onsip/SIP.js#960]
**Describe the enhancement request**
```session.sessionDescriptionHandler.remoteMediaStream``` is not populated with all the video streams. When a session is re-invited with more than one video stream, only the last video stream is active, and only the last video stream is added to session.sessionDescriptionHandler.remoteMediaStream as a track.

**Logs**
![image](https://user-images.githubusercontent.com/58937573/141973978-a6b72ff4-2b52-4719-834a-03ecd90df02c.png)

**To Reproduce (if possible)**
1) Re-invte the session with more then one video stream, and attach a handler for addtrack to the PeerConnection.
2) ```console.log(session.sessionDescriptionHandler.remoteMediaStream.getVideoTracks());```

**Expected behavior**
```session.sessionDescriptionHandler.remoteMediaStream.getVideoTracks()``` should be populated with all the video tacks in that session. 

**Observed behavior**
Only the last video track in the SDP is included in the array. Others are stopped.

**Comment by john-e-riordan** [comment]
Correct. But this is not a bug. The `SessionDescriptionHandler` included with the project only supports up to one audio and/or on video track - there is only ever at most one audio track and/or one video track associated with the `remoteMediaStream` (the last track added). I'm going to update the documentation to make this more clear.

The session description handler architecture exists to allow users to write their own and this enhancement can be dealt with in that fashion without making any changes to the current library. Regardless, a session description handler which supports multiple audio/video tracks is an enhancement request and would be interested in looking at a pull request, but otherwise this is low on the list of things to do (at least the to do list I'm working on).

**Comment by InnovateAsterisk** [comment]
Thanks, In the end I made use of my own code to overcome this.
